# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

  # ----------------------------------------------------------------------------
  # Remote

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.2.0"
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.4.0"
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/frnmst/md-toc
    rev: "8.1.2"
    hooks:
      - id: md-toc
        args: [-p, -s, "1", github]

  # ----------------------------------------------------------------------------
  # Local

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        require_serial: true
        types: [executable, text]
        language: system
        entry: shellcheck --external-sources --shell=bash

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        require_serial: true
        types: [executable, text]
        language: system
        entry: shfmt -s -bn -sr -i 4 -w

  # ----------------------------------------------------------------------------

exclude: |
  (?x)(
    ^CHANGELOG.md$
  )
