# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

  # ----------------------------------------------------------------------------
  # Remote

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint

  # ----------------------------------------------------------------------------
  # Local

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        require_serial: true
        types: [executable, text]
        language: system
        entry: shellcheck --external-sources --shell=bash

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        require_serial: true
        types: [executable, text]
        language: system
        entry: shfmt -s -bn -sr -i 4 -w

  # ----------------------------------------------------------------------------

exclude: |
  (?x)(
    ^CHANGELOG.md$
  )
