plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogTitle: "# Changelog\n\n"
  - "@semantic-release/github"
  - "@semantic-release/git"
