# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on:
  workflow_dispatch:
  push:

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: asdf-vm/actions/install@v1

      - run: bin/shellcheck

      - run: bin/shfmt

      - uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.4.7
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
