# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on:
  workflow_dispatch:
  push:

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: asdf-vm/actions/install@v1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup pre-commit
        run: |
          pip install pre-commit
          pre-commit install

      - name: Configure cache for pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit

      - run: pre-commit run --all-files --verbose --show-diff-on-failure

      - uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.4.7
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
