# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v1

      - name: Run ShellCheck
        run: bin/shellcheck

      - name: Run shfmt
        run: bin/shfmt
