# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: main

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v1

      - name: Run ShellCheck
        run: bin/shellcheck

      - name: Run shfmt
        run: bin/shfmt

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
